<?php

/**
 * Implements hook_permission().
 */
function msu_www_permission() {
  $permissions = array();

  drupal_alter('msu_www_permission', $permissions);

  return $permissions;
}

/**
 * Implements hook_form_FORM_ID_alter() for the node type form.
 */
function msu_www_form_node_type_form_alter(&$form, &$form_state, $form_id) {
  $form['msu_www'] = array(
    '#type' => 'fieldset',
    '#title' => t("McNeese WWW"),
    '#description' => t("Provides McNeese WWW content-type-specific settings, if any such functionality is available."),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#tree' => TRUE,
    '#group' => 'additional_settings',
  );

  $form['#submit'][] = 'msu_www_node_type_form_submit';

  drupal_alter('msu_www_node_type_form', $form, $form_state, $form_id);

  return $form;
}

/**
 * Handles submitting the MSU WWW specific node type settings.
 *
 * @param array $form
 *   A form array
 * @param array $form_state
 *   A form state
 */
function msu_www_node_type_form_submit($form, &$form_state) {
  $function_history = array();
  cf_error_append_history($function_history, __FUNCTION__);

  drupal_alter('msu_www_node_type_form_submit', $form, $form_state);
}
