<?php
// $Id$

/**
 *  @file
 *  Integrating Msu-slider with Views jQFX.
 */

/**
 * Implements hook_theme().
 */
function views_jqfx_msu_slider_theme($existing, $type, $theme, $path) {
  return array(
    'views_jqfx_msu_slider' => array(
      'variables' => array('view' => NULL, 'options' => array(), 'rows' => array(), 'title' => ''),
      'template' => 'views-jqfx-msu-slider',
      'file' => 'views_jqfx_msu_slider.theme.inc',
      'path' => $path . '/theme',
    ),
  );
}
