<?php

/**
 * DEPRECATED, use views_get_view_result(); instead.
 *
 * Provide a simple means to get the raw results from some view.
 * This always returns an array.
 *
 * Why:
 *   There are many cases where one needs to call views manually and views_embed_view does not produce the desired output.
 *
 * @param $view_name
 *   computer name of the view
 * @param $view_display
 *   (optional) name of the display if not using default
 * @param $view_arguments
 *   (optional) an array of every argument to be passed to the view
 * @param $view_reset_cache
 *   (optional) boolean that represents whether to use reset cache or use cache when calling thing
 * @param $function_history
 *   (optional) array of function names, ie: array('0' => 'my_function_name')
 *
 * @return
 *   An array of all rows returned by the requested view.
 */
function cf_views_get_view($view_name, $view_display = 'default', $view_arguments = array(), $view_reset_cache = TRUE, array $function_history = array()){
  watchdog('deprecated', t("cf_views_get_view() has been deprecated in favor of views_get_view_result(), please replace all calls to cf_views_get_view() because it will be removed in the future."));

  if (cf_is_empty_or_non_string(__FUNCTION__, 'view_name', $view_name, WATCHDOG_ERROR, $function_history)){
    return array();
  }

  $results = array();

  $view = views_get_view($view_name, $view_reset_cache);

  if (is_object($view)){
    if (is_string($view_display) && $view_display != ''){
      $view->set_display($view_display);
    }

    if (is_array($view_arguments) && count($view_arguments) > 0){
      $view->set_arguments($view_arguments);
    }

    $view->execute_display();

    if (is_array($view->result)){
      $results = $view->result;
    }

    $view->destroy();
  }

  return $results;
}
