<?php

/**
 * @file
 * McNeese State University Content module.
 */

/**
 * @defgroup mcneese_content McNeese Content
 * @{
 * Provides content functionality and changes to drupal 7.
 */

/**
 * Implements hook_init().
 */
function mcneese_content_init() {
  global $is_https;

  if (!$is_https && basename($_SERVER['PHP_SELF']) == 'index.php' && php_sapi_name() != 'cli') {
    mcneese_content_secure_pages();
  }
}

/**
 * Implements hook_permission().
 */
function mcneese_content_permission() {
  $permissions = array();

  drupal_alter('mcneese_content_permission', $permissions);

  return $permissions;
}

/**
 * Implements hook_form_FORM_ID_alter() for the node type form.
 */
function mcneese_content_form_node_type_form_alter(&$form, &$form_state, $form_id) {
  $form['mcneese_content'] = array(
    '#type' => 'fieldset',
    '#title' => t("McNeese"),
    '#description' => t("Provides McNeese content-type-specific settings, if any such functionality is available."),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#tree' => TRUE,
    '#group' => 'additional_settings',
  );

  $form['#submit'][] = 'mcneese_content_node_type_form_submit';

  drupal_alter('mcneese_content_node_type_form', $form, $form_state, $form_id);

  return $form;
}

/**
 * Handles submitting the McNeese specific node type settings.
 *
 * @param array $form
 *   A form array
 * @param array $form_state
 *   A form state
 */
function mcneese_content_node_type_form_submit($form, &$form_state) {
  drupal_alter('mcneese_content_node_type_form_submit', $form, $form_state);
}

/**
 * Performs a redirect for certain pages at insecure paths to secure paths.
 *
 * This is based on the securepages drupal module.
 */
function mcneese_content_secure_pages() {
  global $base_url, $base_path, $is_https;

  if (drupal_is_front_page()) return;

  $path = isset($_GET['q']) ? $_GET['q'] : '';
  $normal = drupal_get_normal_path($path);

  $secure_path_regex = array();
  $secure_path_regex[] = '^(admin|login|user)($|/.*$|\?.*$)';
  $secure_path_regex[] = '^node/\d+/(edit|draft|webform|webform-\w+\b|accessibility|moderation|revisions|delete|undelete|devel)';

  foreach ($secure_path_regex as $regex) {
    $matched = preg_match('@' . $regex . '@i', $normal);

    if ($matched) {
      $fixed_base_url = preg_replace('@^http://@i', 'https://', $base_url);
      $new_uri = $fixed_base_url . $base_path . $normal;
      if (!headers_sent()) header('Location: ' . $new_uri, TRUE, 301);
      drupal_exit($new_uri);
    }
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * This is based on the webform_ssl drupal module.
 */
function mcneese_content_form_webform_client_form_alter(&$form, &$form_state) {
  global $base_url, $base_path, $is_https;

  if ($is_https) {
    // make sure webform links go to https pages
    $form['#https'] = TRUE;
    $form['#submit'][] = 'mcneese_content_webform_client_form_submit';
  }
  else {
    // if webforms are not already in https connections, then force them to be.
    $path = isset($_GET['q']) ? $_GET['q'] : '';
    $normal = drupal_get_normal_path($path);

    $fixed_base_url = preg_replace('@^http://@i', 'https://', $base_url);
    $new_uri = $fixed_base_url . $base_path . $normal;
    if (!headers_sent()) header('Location: ' . $new_uri, TRUE, 301);
    drupal_exit($new_uri);
  }
}

/**
 * Custom form submit handler for the webform client form.
 *
 * This is based on the webform_ssl drupal module.
 *
 * @see mcneese_content_form_webform_client_form_alter()
 */
function mcneese_content_webform_client_form_submit($form, &$form_state) {
  // If we're staying on the current page, there's no need to modify anything.
  if (!isset($form_state['redirect'])) {
    return;
  }

  if (!is_array($form_state['redirect'])) {
    $form_state['redirect'] = array($form_state['redirect']);
  }

  // After the form is submitted, make sure the page we redirect to is secure.
  // This is necessary so that any confirmation messages that are intended to
  // be displayed to the user via drupal_set_message() are stored in the same
  // session and actually displayed to the user when they are supposed to be.
  $form_state['redirect'][1]['https'] = TRUE;
}


/**
 * @} End of '@defgroup mcneese_content McNeese Content'.
 */
