<?php

/**
 * @file
 * McNeese State University Content module.
 */

/**
 * @defgroup mcneese_content McNeese Content
 * @{
 * Provides content functionality and changes to drupal 7.
 */

/**
 * Implements hook_permission().
 */
function mcneese_content_permission() {
  $permissions = array();

  drupal_alter('mcneese_content_permission', $permissions);

  return $permissions;
}

/**
 * Implements hook_form_FORM_ID_alter() for the node type form.
 */
function mcneese_content_form_node_type_form_alter(&$form, &$form_state, $form_id) {
  $form['mcneese_content'] = array(
    '#type' => 'fieldset',
    '#title' => t("McNeese"),
    '#description' => t("Provides McNeese content-type-specific settings, if any such functionality is available."),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#tree' => TRUE,
    '#group' => 'additional_settings',
  );

  $form['#submit'][] = 'mcneese_content_node_type_form_submit';

  drupal_alter('mcneese_content_node_type_form', $form, $form_state, $form_id);

  return $form;
}

/**
 * Handles submitting the McNeese specific node type settings.
 *
 * @param array $form
 *   A form array
 * @param array $form_state
 *   A form state
 */
function mcneese_content_node_type_form_submit($form, &$form_state) {
  $function_history = array();
  cf_error_append_history($function_history, __FUNCTION__);

  drupal_alter('mcneese_content_node_type_form_submit', $form, $form_state);
}

/**
 * @} End of '@defgroup mcneese_content McNeese Content'.
 */
