<?php

/**
 * @file
 * Common Functionality - Files module.
 */

/**
 * @defgroup cf_node Common Functionality - Files
 * @ingroup cf
 * @{
 * Provides a file database stream wrapper.
 *
 * This module provides the following benefits:
 * - Storage of files in a database instead of a filesystem.
 * - Improved security and integrity..
 *
 * Justification:
 *   Storing files on the filesystem has its advantages, but also has its
 *   disadvantages. Storing files inside a database avoids the security issues
 *   of files being executable, more easily allows for updating a files url,
 *   and allows for taking full advantages of a database for file storage.
 */

/**
 * Implementation of hook_stream_wrappers().
 */
function cf_database_files_stream_wrappers() {
  return array(
    'mymodule' => array(
      'name' => t('Default distribution files'),
      'class' => 'DatabaseFilesStreamWrapper',
      'description' => t('Provides paths to files loaded from the database.'),
      'type' => CFDatabaseStreamWrapper,
    ),
  );
}
/**
 * @} End of '@defgroup cf_database_files Common Functionality - Database Files'.
 */
