<?php
// from: http://drupal.org/node/266332#comment-4315014

/**
 * Implementation of hook_menu().
 */
function menu_link_allow_files_menu() {
  $items = array();
  $file_directory_path = 'sites/default/files'; // FIXME: this is hardcoded, it should not be.

  if (!empty($file_directory_path)){
    $items[$file_directory_path] = array(
      'page callback' => 'drupal_not_found',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
  }

  return $items;
}
