<?php

/**
 * Returns the expected path to the phplot library.
 *
 * @param $function_history
 *   (optional) array of function names, ie: array('0' => 'my_function_name')
 */
function phplot_wrapper_library_path(array $function_history = array()){
  $library_path = libraries_get_path('phplot');

  return $library_path . '/phplot.php';
}

/**
 * Loads the quail library.
 *
 * @param $function_history
 *   (optional) array of function names, ie: array('0' => 'my_function_name')
 */
function phplot_wrapper_include_library(array $function_history = array()) {
  static $loaded_phplot_wrapper_library_includes = FALSE;
  $function_history[] = __FUNCTION__;

  if ($loaded_phplot_wrapper_library_includes) return TRUE;
  $loaded_phplot_wrapper_library_includes = TRUE;

  $library_path = libraries_get_path('quail');

  $result = require_once phplot_wrapper_library_path($function_history);

  return $result;
}
